### ISSUE TITLE
LuaLock not working on a cluster

### ISSUE THREAD

**Issue by ttecles** [alisaifee/coredis#119]
I have implemented this simple code:

```python
@pytest.fixture
async def redis_client() -> redis.RedisCluster:
    return RedisCluster(host=host, port=port, decode_responses=decode_responses)

async def test_lock(redis_client):
    from coredis.recipes.locks import LuaLock
    async with LuaLock(redis_client, 'OUR-SEQUENCE-KEY'):
        current_value = await redis_client.get('OUR-SEQUENCE-KEY')
        next_value = int(current_value) + 1
        await redis_client.set('OUR-SEQUENCE-KEY', next_value)

```

but I am getting the following error:

```
test_session.py::test_session_can_save_a_product_with_images FAILED      [100%]
tests/integration/test_session.py:11 (test_session_can_save_a_product_with_images)
Traceback (most recent call last):
  File "/home/joan/apps/product-images/tests/integration/test_session.py", line 18, in test_session_can_save_a_product_with_images
    async with LuaLock(redis_client, 'OUR-SEQUENCE-KEY'):
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/recipes/locks/lua_lock.py", line 128, in __aenter__
    if await self.acquire():
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/recipes/locks/lua_lock.py", line 159, in acquire
    if await self.__acquire(token, stop_trying_at):
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/recipes/locks/lua_lock.py", line 216, in __acquire
    return await self.client.set(
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/commands/_validators.py", line 90, in wrapped
    return await func(*args, **kwargs)
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/commands/_wrappers.py", line 196, in wrapped
    async with command_cache(callable, *args, **kwargs) as response:
  File "/home/joan/.pyenv/versions/3.10.5/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/commands/_wrappers.py", line 90, in __call__
    yield await func(*args, **kwargs)
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/commands/core.py", line 638, in set
    return await self.execute_command(
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/_utils.py", line 167, in inner
    return await func(*args, **kwargs)
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/client/cluster.py", line 696, in execute_command
    node = self.connection_pool.get_node_by_slot(slot, command)
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/pool/cluster.py", line 418, in get_node_by_slot
    return self.get_primary_node_by_slot(slot)
  File "/home/joan/virtualenvs/product-images/lib/python3.10/site-packages/coredis/pool/cluster.py", line 397, in get_primary_node_by_slot
    return self.nodes.slots[slot][0]
KeyError: 5195
```

I am using [this](https://hub.docker.com/r/bitnami/redis-cluster/) as a Redis Cluster Image

**Comment by alisaifee** [comment]
This actually seems like the cluster isn't completely initialized at the time `test_lock` runs.

I was able to run a variant of your example:

```
async def test():
    from coredis.recipes.locks import LuaLock
    redis_client = coredis.RedisCluster('localhost', 7000)
    async with LuaLock(redis_client, 'OUR-SEQUENCE-KEY'):
        current_value = await redis_client.get('OUR-SEQUENCE-KEY-2')
        next_value = int(current_value or 0) + 1
        await redis_client.set('OUR-SEQUENCE-KEY-2', next_value)
```

How are you starting up redis-cluster before running pytest? 

As an example in coredis' tests - the `redis_cluster` fixture isn't provided to the test until the cluster is stable ([reference](https://github.com/alisaifee/coredis/blob/master/tests/conftest.py#L195))

**Comment by ttecles** [comment]
I think you are right. Cause `SET` command doesn't work either. Taking a look at it. Thanks

**Comment by ttecles** [comment]
> I think you are right. Cause `SET` command doesn't work either. Taking a look at it. Thanks
 closing the issue
