### ISSUE TITLE
New instance of #143 -- Unable to map [] to int

### ISSUE THREAD

**Issue by coandco** [alisaifee/coredis#191]
## Expected Behaviour

Coredis calls (such as LLEN, HGETALL, etc) should work as advertised

## Current Behaviour

When this bug is triggered, all coredis calls attempt to coerce the result into int, even if it doesn't make sense

## Steps to Reproduce

Unfortunately, I don't have any idea how to reproduce this.  It seemingly happened out of the blue after my service had been running for a couple of months, and other copies of the service that talk to the same Redis server didn't have any issue.

## Your Environment

- coredis version: 4.10.1
- Redis version: 6.0.16
- Operating system: Debian 11
- Python version: 3.9.16

I believe I just hit the same bug as #143!  I'm running coredis 4.10.1 in a long-running service, and suddenly started getting lots of errors about coredis being unable to map all kinds of responses to `int`.  Here are some of the stacktraces:

```
2023-10-10 13:40:48,776 - Pushit - ERROR - Error in maintenance loop: 'int' object is not iterable
Traceback (most recent call last):
  File "/etc/pushit/pushitpy.py", line 286, in maintenance_loop
    for message in await redis_cluster.lrange(self.working_queue, 0, -1):
TypeError: 'int' object is not iterable

2023-10-10 13:40:55,536 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/root/.local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/etc/pushit/pushitpy.py", line 590, in healthcheck
    send_queue_length = await asyncio.wait_for(rclient.llen(pushit_obj.send_queue), 1)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/root/.local/lib/python3.9/site-packages/coredis/commands/_wrappers.py", line 196, in wrapped
    async with command_cache(callable, *args, **kwargs) as response:  # type: ignore
  File "/usr/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/root/.local/lib/python3.9/site-packages/coredis/commands/_wrappers.py", line 90, in __call__
    yield await func(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/coredis/commands/core.py", line 3244, in llen
    return await self.execute_command(CommandName.LLEN, key, callback=IntCallback())
  File "/root/.local/lib/python3.9/site-packages/coredis/_utils.py", line 167, in inner
    return await func(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/coredis/client/cluster.py", line 737, in execute_command
    response = callback(
  File "/root/.local/lib/python3.9/site-packages/coredis/response/_callbacks/__init__.py", line 84, in __call__
    return self.transform_3(cast(RESP3, response), **options)
  File "/root/.local/lib/python3.9/site-packages/coredis/response/_callbacks/__init__.py", line 92, in transform_3
    return self.transform(cast(RESP, response), **options)
  File "/root/.local/lib/python3.9/site-packages/coredis/response/_callbacks/__init__.py", line 278, in transform
    raise ValueError(f"Unable to map {response!r} to int")
ValueError: Unable to map [] to int
```

While this was going on, I used aioconsole to interact with the application and test out some commands.  What I saw was that the coredis client was returning 0 for everything:
```
>>> await rclient.llen(pushit.working_queue)
0
>>> await rclient.lrange(pushit.working_queue, 0, -1)
0
>>> await rclient.hgetall(pushit.retries_hash)
0
```

Once I restarted the service (and thus reinitialized the coredis client), the problem went away:
```
>>> await rclient.llen(pushit.working_queue)
0
>>> await rclient.lrange(pushit.working_queue, 0, -1)
[]
```

I have more stacktraces where the one above came from if they'd help.

**Comment by coandco** [comment]
Oh, looking at the most recent release (4.16.0), it looks like it might have fixed this problem:
```
Fix intermittent errors due to mismatched responses when multiple
coroutines access a new connection pool.
```

I'll update to the latest coredis and reopen this if I hit it again.
