### ISSUE TITLE
coredis requires `wheel` to build from source

### ISSUE THREAD

**Issue by Le0Developer** [alisaifee/coredis#43]
coredis requires `wheel` to build from source but it's not listed as requirement.

without `pip install wheel` installation from source fails

**Comment by Le0Developer** [comment]
```py
pi@rasp-0w-01:~ $ pip3.10 install coredis
Defaulting to user installation because normal site-packages is not writeable
Collecting coredis
  Downloading coredis-3.4.0.tar.gz (152 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.5/152.5 KB 771.3 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [6 lines of output]
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help
      
            error: invalid command 'bdist_wheel'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for wrapt
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/local/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpn5_9b71j', '--quiet', 'wrapt<2,>=1.1.0']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-trjfjmyz/coredis_1a98c79e889c459eb106190f29a8246d/setup.py", line 104, in <module>
          setup(
        File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "/usr/local/lib/python3.10/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/usr/local/lib/python3.10/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/usr/local/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpn5_9b71j', '--quiet', 'wrapt<2,>=1.1.0']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
pi@rasp-0w-01:~ $ pip3.10 install wheel
Defaulting to user installation because normal site-packages is not writeable
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.37.1
pi@rasp-0w-01:~ $ pip3.10 install coredis
Defaulting to user installation because normal site-packages is not writeable
Collecting coredis
  Using cached coredis-3.4.0.tar.gz (152 kB)
  Preparing metadata (setup.py) ... done
Collecting deprecated>=1.2
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting typing_extensions>=4.1.1
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting packaging<22,>=21
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting wrapt<2,>=1.1.0
  Using cached wrapt-1.14.0-cp310-cp310-linux_armv6l.whl
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.8-py3-none-any.whl (98 kB)
Building wheels for collected packages: coredis
  Building wheel for coredis (setup.py) ... done
  Created wheel for coredis: filename=coredis-3.4.0-cp310-cp310-linux_armv6l.whl size=152543 sha256=458b2621ebbf76fccae2b7790603597727ff28e7ea171b829c64ca419f7c6277
  Stored in directory: /home/pi/.cache/pip/wheels/64/a2/6f/8ac526c975535db1319942371730e7824fc22a25ec3a32a3f7
Successfully built coredis
Installing collected packages: wrapt, typing_extensions, pyparsing, packaging, deprecated, coredis
Successfully installed coredis-3.4.0 deprecated-1.2.13 packaging-21.3 pyparsing-3.0.8 typing_extensions-4.1.1 wrapt-1.14.0
pi@rasp-0w-01:~ $ 

```

**Comment by Le0Developer** [comment]
All of these work without wheel. I never needed to install wheel explicitly before, so I think that says a lot.
```
hikari==2.0.0.dev108
python-Levenshtein==0.12.2
quickjs>=1.16,<1.19
emoji>=1.6,<1.8
python-dotenv>=0.19,<0.21
sentry_sdk>=1.5,<1.6
janus>=1.0,<1.1
msgpack>=1,<1.1
pydantic>=1.9,<1.10
fastapi>=0.74,<0.76
httpx>=0.22,<0.23
```
I feel like this issue might be related to wrapt due to the way it appears in the error log.

**Comment by alisaifee** [comment]
can you install wrapt directly? How about the official redis library?

**Comment by alisaifee** [comment]
I've made a few minor simplifications in the setup.py & the package info (though there's no particularly good reason that I can understand why any of those changes would directly impact a change in how pip decides to build the source distribution).

You can try out the source dist in test pypi from here: https://test.pypi.org/project/coredis/3.4.0.post0.dev9/#files

**Comment by Le0Developer** [comment]
Getting an error trying to install from there:
```py
(env) pi@rasp-3b-02:~/testing $ pip3.10 install -i https://test.pypi.org/simple/ coredis==3.4.0.post0.dev9
Looking in indexes: https://test.pypi.org/simple/
Collecting coredis==3.4.0.post0.dev9
  Downloading https://test-files.pythonhosted.org/packages/62/8d/c31c1cf2cdbcfb3534bb2845490916b40cb19dad07ae3fa1312fe1192407/coredis-3.4.0.post0.dev9.tar.gz (152 kB)
     |████████████████████████████████| 152 kB 3.3 MB/s 
ERROR: Could not find a version that satisfies the requirement deprecated>=1.2 (from coredis) (from versions: none)
ERROR: No matching distribution found for deprecated>=1.2
```
But installing from source works now: (didnt work before)
```py
(env) pi@rasp-3b-02:~/coredis $ pip3.10 install .
Processing /home/pi/coredis
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Collecting deprecated>=1.2
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting typing_extensions>=4.1.1
  Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting packaging<22,>=21
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 914 kB/s 
Collecting wrapt<2,>=1.1.0
  Downloading wrapt-1.14.0.tar.gz (50 kB)
     |████████████████████████████████| 50 kB 1.7 MB/s 
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.8-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 1.6 MB/s 
Using legacy 'setup.py install' for coredis, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
Installing collected packages: wrapt, pyparsing, typing-extensions, packaging, deprecated, coredis
    Running setup.py install for wrapt ... done
    Running setup.py install for coredis ... done
Successfully installed coredis-3.4.1 deprecated-1.2.13 packaging-21.3 pyparsing-3.0.8 typing-extensions-4.1.1 wrapt-1.14.0
```

**Comment by Le0Developer** [comment]
Thanks for helping!
